# SELinux userspace portions originally by Nicolas Iooss
# from: https://github.com/fishilico/selinux-refpolicy-patched/blob/travis-upstream/.travis.yml
---

language: python

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pep8
  - TOX_ENV=coverage
  - TOX_ENV=lint

matrix:
  allow_failures:
    - env: TOX_ENV=coverage

before_install:
  - lsb_release -a
  - bison -V
  - flex -V
  - sudo apt-get update -qq

  # Install SELinux userspace utilities dependencies
  - sudo apt-get install -qq libaudit-dev libcap-ng-dev libustr-dev libpcre3-dev

  # Install newer swig
  - curl -sS -L http://prdownloads.sourceforge.net/swig/swig-3.0.8.tar.gz | tar xz
  - cd swig-3.0.8
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Download current SELinux userspace tools and libraries
  #- git clone https://github.com/SELinuxProject/selinux.git selinux-src -b libsepol-2.7
  - git clone https://github.com/SELinuxProject/selinux.git selinux-src

  # Ubuntu 12.04 coreutils is too old to provide "ln --relative" :(
  - sed -i -e '/$(LN) -sf/s/--relative//' selinux-src/libsepol/src/Makefile
  - sed -i -e '/ln -sf/s/--relative//' selinux-src/libselinux/src/Makefile

  # Only portions of the toolchain are necessary
  - sed -i -e 's/^SUBDIRS=.*/SUBDIRS=libsepol libselinux checkpolicy/' selinux-src/Makefile

  # Compile and install SELinux toolchain
  # On Ubuntu 12.04, default CFLAGS make the build fail in libsepol/cil with:
  #    error: declaration of 'index' shadows a global declarationo
  - sudo make CFLAGS="-O2 -pipe -fPIC -Wall" -C selinux-src install

  # Ubuntu 12.04's flex generates a redundant decl in libqpol
  - sed -i -e "/Wwrite-strings/s/,/, '-Wno-redundant-decls',/" setup.py

install:
  - pip install tox

script:
  - tox --version
  - tox -e $TOX_ENV
