# SELinux userspace portions originally by Nicolas Iooss
# from: https://github.com/fishilico/selinux-refpolicy-patched/blob/travis-upstream/.travis.yml
---

language: python

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pep8
  - TOX_ENV=coverage
  - TOX_ENV=lint

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=coverage

sudo: required
dist: trusty

addons:
  apt:
    packages:
    # Install SELinux userspace utilities dependencies
    - bison
    - flex
    - gettext
    - libaudit-dev
    - libbz2-dev
    - libustr-dev
    - libpcre3-dev

before_install:
  - lsb_release -a
  - bison -V
  - flex -V
  - python -V

install:
  - SELINUX_USERSPACE_VERSION=libsepol-2.7

  # Install newer swig
  - curl -sS -L http://prdownloads.sourceforge.net/swig/swig-3.0.8.tar.gz | tar xz
  - cd swig-3.0.8
  - ./configure
  - make
  - sudo make install
  - cd ..

  # Download current SELinux userspace tools and libraries
  - git clone https://github.com/SELinuxProject/selinux.git selinux-src -b ${SELINUX_USERSPACE_VERSION}

  # Only portions of the toolchain are necessary
  - sed -i -e 's/^SUBDIRS=.*/SUBDIRS=libsepol libselinux checkpolicy/' selinux-src/Makefile

  # Compile and install SELinux toolchain
  # On Ubuntu 12.04, default CFLAGS make the build fail in libsepol/cil with:
  #    error: declaration of 'index' shadows a global declarationo
  - sudo make CFLAGS="-O2 -pipe -fPIC -Wall" -C selinux-src install

  # Ubuntu 12.04's flex generates a redundant decl in libqpol
  - sed -i -e "/Wwrite-strings/s/,/, '-Wno-redundant-decls',/" setup.py

  - pip install tox

script:
  - tox --version
  - tox -e $TOX_ENV

after_failure:
  - cat "${TRAVIS_BUILD_DIR}/.tox/tox-0.log"
